#!/usr/bin/env bash
set -euo pipefail

: "${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is required}"

: "${ANALYTICS_DB_USERNAME:?ANALYTICS_DB_USERNAME is required}"
: "${ANALYTICS_DB_PASSWORD:?ANALYTICS_DB_PASSWORD is required}"
: "${ANALYTICS_DB_NAME:=${ANALYTICS_DB_USERNAME}}"

: "${KNOWLEDGE_BASE_DB_USERNAME:?KNOWLEDGE_BASE_DB_USERNAME is required}"
: "${KNOWLEDGE_BASE_DB_PASSWORD:?KNOWLEDGE_BASE_DB_PASSWORD is required}"
: "${KNOWLEDGE_BASE_DB_NAME:=${KNOWLEDGE_BASE_DB_USERNAME}}"

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL

CREATE DATABASE IF NOT EXISTS \`${KNOWLEDGE_BASE_DB_NAME}\`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${KNOWLEDGE_BASE_DB_USERNAME}'@'%' IDENTIFIED BY '${KNOWLEDGE_BASE_DB_PASSWORD}';
ALTER USER '${KNOWLEDGE_BASE_DB_USERNAME}'@'%' IDENTIFIED BY '${KNOWLEDGE_BASE_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${KNOWLEDGE_BASE_DB_NAME}\`.* TO '${KNOWLEDGE_BASE_DB_USERNAME}'@'%';

CREATE DATABASE IF NOT EXISTS \`${ANALYTICS_DB_NAME}\`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${ANALYTICS_DB_USERNAME}'@'%' IDENTIFIED BY '${ANALYTICS_DB_PASSWORD}';
ALTER USER '${ANALYTICS_DB_USERNAME}'@'%' IDENTIFIED BY '${ANALYTICS_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${ANALYTICS_DB_NAME}\`.* TO '${ANALYTICS_DB_USERNAME}'@'%';

FLUSH PRIVILEGES;
SQL
